language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m

before_script:
  - composer self-update
  - composer install --prefer-dist -n

script:
  - ./vendor/bin/phpunit tests/ --coverage-clover clover.xml
  - ./vendor/bin/phpcs --extensions=php --standard=PSR12 --ignore=*/_files/* src/ tests/
  - ./vendor/bin/phpmd ./src text ./phpmd.xml --suffixes php

after_success:
  - travis_retry php vendor/bin/coveralls -v -x clover.xml
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
